### ISSUE TITLE
Right-click (context) menu for links within embed

### ISSUE THREAD

**Issue by imrehg** [Seraphli/obsidian-link-embed#15]
When in editing mode / Live Preview in Obsidian, a regular link's menu pops up a bunch of things, including copying the URL. 

<img width="533" alt="Screenshot 2023-02-15 at 13 12 01" src="https://user-images.githubusercontent.com/38863/218938409-6d6edf43-8cc5-4f35-a9c1-b7a8666433bb.png">

The the embedded link's context menu on the other hand doesn't show that

<img width="737" alt="Screenshot 2023-02-15 at 13 13 02" src="https://user-images.githubusercontent.com/38863/218938793-8ad73d7b-3f99-4cb3-a1ea-d1c4f8b09394.png">

In "reading mode as well, a regular link has an option to "copy" it

<img width="315" alt="Screenshot 2023-02-15 at 13 11 36" src="https://user-images.githubusercontent.com/38863/218938890-129614aa-2b86-46dc-9990-da1b830f6518.png">

while the embed has nothing, I can only click it.

Thus it's much more difficult to get a link out of the embed, especially if I don't want to open it at the moment. And the "open in browser & then copy" way is not convenient.

**Comment by Seraphli** [comment]
You can easily copy the URL by clicking the `edit this block` on the right top. You can also place the cursor upside or downside of the block and move the cursor into the block to turn it into a markdown block, then you can copy the URL. Meanwhile, I will check if there is a way to change the context menu. I can not guarantee it now.

**Comment by Seraphli** [comment]
I tried and didn't find a way to implement this feature. Because the preview part is rendered in `Live Preview` mode, there is no API to get the HTML element that you are hovering over. So I can not determine the URL. I tried to get the cursor, but the return is not related to your real cursor position. A regular link's menu can be changed because it directly selects the URL in the editor, and there is an API to extract the selections from the editor.
