### ISSUE TITLE
Feature Request: Save thumbnail image locally

### ISSUE THREAD

**Issue by utopicchaotica** [Seraphli/obsidian-link-embed#19]
It would be nice to have this optional feature as it would help with load times (not pulling files from the internet, especially if you have limited bandwidth and/or have poor speeds).

**Comment by Seraphli** [comment]
I create this plugin mainly trying to save text information on the website, so that I can search them later. Image, however, is not quite important compared to title or description, since you can not search them. They are just for good looking, which make this plugin more like the way in Notion.
Besides, saving all images in the vault will make the vault much larger, and syncing it on a new machine will be slower under limited bandwidth.
