### ISSUE TITLE
Render preview card without changing document

### ISSUE THREAD

**Issue by robertandrews** [Seraphli/obsidian-link-embed#28]
I love the idea of these Notion-style link preview cards. It looks really good.

But I would rather they are rendered without having to hard-code information into the note file.

Is it possible to leave only the URL in place and just call the URL, it information and render the card upon loading the note/adding a URL?

To stop this happening for every link, maybe it's possible to include a simple attribute within link mark-up?

**Comment by Seraphli** [comment]
Storing metadata like descriptions was the main reason why I started this project, so that I could search with more related keywords later. So yes, that is possible, but I'm probably not going to implement that. But you are welcome to make a pull request about this. You can add an option to toggle this feature.
